M48
; DRILL file {KiCad (6.0.6)} date Fri Jul 22 01:14:51 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-22T01:14:51+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X4.7Y-3.15
X4.7Y-3.25
X4.7Y-3.35
X4.7Y-3.45
X4.7Y-3.55
X5.4Y-3.1498
X5.4Y-3.2498
X5.4Y-3.3498
X5.4Y-3.4498
X5.4Y-3.5498
T0
M30
